### PR TITLE
add a post on what we learned regarding ops

### PR DESCRIPTION
**Pull request by jnizet**
DO NOT MERGE until Tuesday. Note that I'll be in the middle of the Red Sea, so I won't be able to merge it.
Feel free to make changes if you feel it's needed.

### CODE REVIEW

**Comment by clacote** [comment]
What I learn from doing Quizzie: your blog posts are amazing! :)

**Comment by jnizet** [comment]
That's sweet, thanks.

2015-03-12 20:50 GMT+01:00 Cyril Lacôte <notifications@github.com>:

**Comment by clacote** [comment]
And shouldn't we detail the part that made us drop Docker definitively? I can't even explain it, but that was something about port exposition between containers, no?

**Comment by jnizet** [comment]
I can't remember it either :(. And I feel that would be too detailed compared to the rest of the post.

**Pull request merged**
