### PR TITLE
chore(config): restore trailing slash aster post URL for Discuss history

### PR DESCRIPTION
**Pull request by clacote**

### CODE REVIEW

**Comment by clacote** [comment]
Merging & deploying before we get a new Discuss comment

**Comment by clacote** [comment]
- Comments are back! \o/ : http://blog.ninja-squad.com/2016/01/20/become-a-ninja-angular-2-ebook-release/#disqus_thread
- URL with trailing slash are OK: http://blog.ninja-squad.com/2016/02/14/cadendrier-formations-debut2016/ :white_check_mark: 
- URL without trailing slash respond (like [the one tweeted this morning](https://twitter.com/ninjasquad/status/699511935142883329)): http://blog.ninja-squad.com/2016/02/14/cadendrier-formations-debut2016 :white_check_mark: 

BUT:
- some pages are failing, like the link to tags on top of a post: http://blog.ninja-squad.com/tags.html#Angular 2-ref :cry:

**Comment by cexbrayat** [comment]
http://blog.ninja-squad.com/archive.html is also down

**Comment by clacote** [comment]
Yes, as for tag.html, a trailing ".html" is wrongly added, where http://blog.ninja-squad.com/archive is OK

**Comment by clacote** [comment]
http://jekyllrb.com/docs/permalinks/#pages-and-collections

**Pull request merged**
