### PR TITLE
Fix tags in old posts (angular2 -> Angular 2, angularjs -> AngularJS, java8 -> Java 8)

### PR DESCRIPTION
**Pull request by clacote**
BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by cexbrayat** [comment]
Maybe we should rename "Angular 2" to "Angular" only, as Angular 3 is not that far?
Otherwise LGTM

**Comment by jnizet** [comment]
Same remark as Cédric.

**Comment by clacote** [comment]
Maybe. And what about setting two tags: `Angular` AND `Angular 2`?

**Comment by cexbrayat** [comment]
Why not? That costs us nothing, and is maybe more 'SEO efficient'

**Comment by clacote** [comment]
That was the point. Will do!

**Comment by clacote** [comment]
Setting `Angular` and `Angular 2` tags done in 19e659a.

**Comment by cexbrayat** [comment]
👍

**Pull request merged**
